const franklyArray = [
  "What’s your biggest fear?",
  "Have you ever lied to a friend?",
  "What's something you've never told anyone?",
  "What’s your biggest insecurity?",
  "Who do you secretly admire?",
  "Have you ever cheated on a test?",
  "What’s the most embarrassing thing you’ve ever done?",
  "Have you ever had a crush on a teacher?",
  "What’s your biggest regret?",
  "What’s one thing you would change about yourself?",
  "Have you ever been jealous of a friend?",
  "What’s a secret talent you’ve never told anyone?",
  "Have you ever pretended to like something to fit in?",
  "Who was your first crush?",
  "Do you stalk people on social media?",
  "Have you ever ghosted someone?",
  "What’s the last lie you told?",
  "Have you ever cried during a movie?",
  "What’s something you’re ashamed of?",
  "What’s the most childish thing you still do?",
  "Have you ever stolen something?",
  "What’s a weird habit you have?",
  "Do you talk to yourself?",
  "What’s the worst date you’ve ever been on?",
  "Who do you trust the least in this room?",
  "What’s your guilty pleasure?",
  "Have you ever sent a message to the wrong person?",
  "What’s the weirdest dream you’ve ever had?",
  "Have you ever been caught lying?",
  "What's a rumor you've heard about yourself?",
  "What’s the most trouble you’ve gotten into?",
  "Do you keep secrets from your parents?",
  "Have you ever had a crush on someone unavailable?",
  "What's your biggest turn-off?",
  "What's your biggest turn-on?",
  "Do you believe in love at first sight?",
  "Who do you miss right now?",
  "What’s a habit you’re trying to break?",
  "What’s the worst thing you’ve done out of anger?",
  "Have you ever broken someone’s heart?",
  "What’s something you’ve never told your ex?",
  "Have you ever been rejected?",
  "What’s the most difficult decision you’ve made?",
  "Have you ever pretended to be sick to skip something?",
  "What do you really think of your closest friend?",
  "What’s something people get wrong about you?",
  "What’s a lie you regret telling?",
  "Have you ever cheated in a relationship?",
  "Who’s someone you envy?",
  "What’s your weirdest pet peeve?",
  "What's your biggest fantasy?",
  "Have you ever been in love?",
  "Who do you think is the most attractive person here?",
  "What's the most illegal thing you've done?",
  "What’s the worst thing you’ve said to someone?",
  "Do you believe in soulmates?",
  "Have you ever been in a toxic relationship?",
  "What’s something you’d do if you knew you’d never get caught?",
  "What’s a lie you tell often?",
  "What’s your most controversial opinion?",
  "Who’s the last person you stalked online?",
  "What’s something you wish people knew about you?",
  "What's a secret you've never told anyone?",
  "Have you ever blackmailed or been blackmailed?",
  "What’s your worst habit?",
  "Do you have a secret crush right now?",
  "Have you ever sabotaged someone?",
  "What’s the most embarrassing thing on your phone?",
  "What’s something you’ve done that you still feel guilty about?",
  "Who’s your celebrity crush?",
  "Have you ever been fired or nearly fired?",
  "What’s your weirdest interest?",
  "Do you ever eavesdrop on conversations?",
  "What’s something you’ve done just for clout?",
  "Do you believe in karma?",
  "Have you ever played dumb to get out of something?",
  "What’s a fear you’ve never shared before?",
  "What's something you hate that everyone else loves?",
  "What’s the worst gift you’ve received?",
  "Have you ever faked emotions?",
  "What’s your most irrational fear?",
  "Do you believe in second chances?",
  "Have you ever laughed at something inappropriate?",
  "What’s the most awkward conversation you’ve had?",
  "What’s a lie you told your best friend?",
  "What’s something you’re hiding from someone right now?",
  "What’s something you did that you’re proud of, but can’t tell anyone?",
  "Have you ever been catfished or catfished someone?",
  "What’s your most embarrassing nickname?",
  "What’s something you don’t like about your personality?",
  "Have you ever crushed on a friend’s partner?",
  "What’s your most dramatic breakup story?",
  "What’s something you wish you never did?",
  "What’s your biggest red flag?",
  "Do you keep any secrets from your family?",
  "What’s the last thing you cried about?",
  "What’s the pettiest reason you stopped talking to someone?",
  "Have you ever been caught spying?",
  "What’s something you do when no one’s watching?",
  "What’s something you’d never admit out loud… until now?"
];

const dareArray = [
  "Send a voice note singing a random song.",
  "Post an embarrassing photo on your story.",
  "Eat a spoonful of mustard.",
  "Text your crush and say 'I like you.'",
  "Speak in an accent for 5 minutes.",
  "Try to lick your elbow (on camera).",
  "Do 20 jumping jacks right now.",
  "Take a silly selfie and send it to the group.",
  "Say the alphabet backward.",
  "Prank call a friend.",
  "Let someone else write your next social media post.",
  "Eat a piece of raw onion.",
  "Talk without closing your mouth for 1 minute.",
  "Balance a book on your head for 30 seconds.",
  "Attempt a TikTok dance.",
  "Wear your clothes backward for the next 15 minutes.",
  "Text someone random 'I know your secret.'",
  "Do your best impression of a celebrity.",
  "Write your name with your non-dominant hand.",
  "Say the first word that comes to mind for 20 seconds.",
  "Draw a self-portrait blindfolded.",
  "Let someone dare you again.",
  "Give a motivational speech about an object nearby.",
  "Gargle water while singing a song.",
  "Eat something without using your hands.",
  "Send the 5th photo in your gallery to the group.",
  "Speak only in song lyrics for 5 minutes.",
  "Imitate an animal until someone guesses it.",
  "Text your ex 'I miss you' then delete it.",
  "Let someone post on your story.",
  "Tell your most embarrassing moment in detail.",
  "Eat something you hate.",
  "Talk like a baby for 3 minutes.",
  "Try to do a handstand or cartwheel.",
  "Do your best evil laugh.",
  "Call someone and confess a fake secret.",
  "Draw a tattoo on yourself with a pen.",
  "Read your last text out loud.",
  "Let the group choose your next status.",
  "Make up a short poem about someone here.",
  "Dance with no music for 1 minute.",
  "Let someone redo your hairstyle.",
  "Wear socks on your hands for the next 10 minutes.",
  "Make a funny face and hold it for 30 seconds.",
  "Tell a joke so bad it’s funny.",
  "Do your best impression of your favorite teacher.",
  "Close your eyes and guess the object handed to you.",
  "Do a runway walk across the room.",
  "Try to touch your nose with your tongue.",
  "Pretend to be a robot for 2 minutes.",
  "Eat something in the weirdest way possible.",
  "Share your screen and show your search history.",
  "Let someone else draw on your face (with washable marker).",
  "Speak like Shakespeare for 5 minutes.",
  "Call someone and confess you like them (even if you don’t).",
  "Let the group decide your dare.",
  "Act like a cat for 2 minutes.",
  "Try to say a tongue twister 5 times fast.",
  "Do your best runway model walk.",
  "Draw something using your feet.",
  "Try to juggle 3 objects.",
  "Show your best dance move.",
  "Balance a spoon on your nose.",
  "Speak only in rhymes for the next round.",
  "Make a dramatic scene with any item nearby.",
  "Show your phone wallpaper and explain it.",
  "Take a ridiculous selfie and make it your profile pic for 10 mins.",
  "Type with your elbows.",
  "Share a random unpopular opinion.",
  "Take a 'cold drink shot' like it’s alcohol.",
  "Let someone write something on your forehead.",
  "Mime an activity and let others guess.",
  "Compliment everyone in the group.",
  "Whisper everything you say for the next 5 minutes.",
  "Rap about your day.",
  "Try to moonwalk.",
  "Speak in slow motion.",
  "Make a ridiculous hat from nearby stuff and wear it.",
  "Act like a YouTuber doing a product review.",
  "Call a friend and speak gibberish until they hang up.",
  "Swap socks with someone.",
  "Put ice down your shirt for 10 seconds.",
  "Record a fake ad for a ridiculous product.",
  "Use a funny filter and take a video.",
  "Make up a song about pizza.",
  "Show the weirdest app on your phone.",
  "Wrap yourself in a blanket and act like a burrito.",
  "Put on as many layers of clothing as possible in 1 minute.",
  "Pretend to cry dramatically for 1 minute.",
  "Say the weirdest compliment you can think of.",
  "Hold a plank for 30 seconds.",
  "Share your most-used emoji.",
  "Do a random TikTok trend.",
  "Paint your nails with a marker.",
  "Balance something on your head while walking.",
  "Try to do a magic trick.",
  "Hum a song and have others guess it.",
  "Show your lock screen.",
  "Pretend to be someone else in the group.",
  "Let someone give you a new nickname."
];
